brew "git"
brew "gh"
brew "fish"
brew "tmux"
brew "neovim"
brew "ripgrep"
brew "fd"
brew "fzf"

# Java backend/client internship baseline.
brew "maven"
brew "gradle"
cask "temurin@21"

cask "google-chrome"
cask "iterm2"
cask "orbstack"
cask "karabiner-elements"
cask "hammerspoon"
cask "rectangle"
cask "snipaste"
cask "raycast"
cask "jetbrains-toolbox"
cask "cursor"
cask "zed"
